"use client";

import { useState } from "react";
import { DocumentRecord, LawyerPreparationOutput, Evidence } from "@/lib/types";
import { Scale, CheckSquare, HelpCircle, FileQuestion, Copy, Check, Sparkles, Loader2, Bookmark, Download, Printer } from "lucide-react";

interface LawyerPrepViewProps {
  document: DocumentRecord;
  evidenceMap: Record<string, Evidence>;
  onSelectEvidence: (ev: Evidence, interpretation?: string, title?: string) => void;
}

export function LawyerPrepView({ document, evidenceMap, onSelectEvidence }: LawyerPrepViewProps) {
  const [data, setData] = useState<LawyerPreparationOutput | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/documents/${document.id}/lawyer-prep`, {
        method: "POST",
      });
      const json = await res.json();
      if (!res.ok || json.error) {
        throw new Error(json.error?.message || "Failed to generate lawyer preparation");
      }
      setData(json.lawyerPreparation);
    } catch (err: any) {
      setError(err.message || "Failed to generate lawyer preparation");
    } finally {
      setLoading(false);
    }
  };

  const generateMarkdownDossier = (): string => {
    if (!data) return "";
    return `# LEGAL COUNSEL BRIEFING DOSSIER
**Document**: ${document.name} (Type: ${document.documentType.toUpperCase()})  
**Document ID**: \`${document.id}\`  
**Generated by**: LexLens Legal Intelligence Platform  
**Date**: ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}  
**Owner / Author**: Alok Ranjan Singh (https://github.com/arsinghin/contract-lens)  

---

## 1. EXECUTIVE SUMMARY & RISK PROFILE
This briefing dossier is prepared for counsel consultation to evaluate contractual enforceability, notice period inconsistencies, restrictive covenants, and missing attachments prior to signature or execution.

- **Document Length**: ${document.pages.length} page(s)
- **Extracted Clauses**: ${document.clauses.length}
- **Operative Obligations**: ${document.obligations.length}
- **High-Severity Risk Findings**: ${document.findings.filter((f) => f.severity === "high").length}

---

## 2. PRIORITIZED QUESTIONS TO DISCUSS WITH COUNSEL
${data.questionsForCounsel
  .map(
    (q, i) => `### Question ${i + 1}
**Question**: ${q.question}
**Legal Context / Rationale**: ${q.reason}
${q.relatedClauseId ? `**Related Clause**: \`${q.relatedClauseId}\`` : ""}
`
  )
  .join("\n")}

---

## 3. ACTIONABLE CONTRACT REVIEW CHECKLIST
| Item | Category | Status |
| :--- | :--- | :--- |
${data.reviewChecklist
  .map(
    (c) => `| ${c.item.replace(/\|/g, "\\|")} | ${c.category} | **${c.status.toUpperCase()}** |`
  )
  .join("\n")}

---

## 4. MISSING INFORMATION & UNATTACHED SCHEDULES
The following schedules, exhibits, or compensation formulas are referenced in the agreement text but were **not attached** or remain **unestablished**:
${data.missingInformation.map((m) => `- [ ] ${m}`).join("\n")}

---

## 5. RELEVANT EXTRACTED OPERATIVE CLAUSES
${document.clauses
  .slice(0, 6)
  .map((c) => {
    const ev = c.evidenceIds[0] ? evidenceMap[c.evidenceIds[0]] : null;
    return `### ${c.title} (${c.category.toUpperCase()})
${ev ? `> "${ev.sourceText.replace(/\n/g, " ")}"` : ""}

*Summary*: ${c.summary}
${c.interpretation ? `*Context*: ${c.interpretation}` : ""}
${ev ? `*Offset Range*: Chars ${ev.startOffset ?? 0}–${ev.endOffset ?? 0} (Page ${ev.pageNumber})` : ""}
`;
  })
  .join("\n")}

---
*Legal Disclaimer: LexLens provides automated structural clause parsing and textual difference identification. This dossier is an assistive intelligence brief for discussion purposes and does not constitute formal legal counsel or create an attorney-client relationship.*
`;
  };

  const handleCopy = () => {
    const text = generateMarkdownDossier();
    if (!text) return;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const text = generateMarkdownDossier();
    if (!text) return;
    const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement("a");
    link.href = url;
    link.download = `${document.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-counsel-brief.md`;
    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="bg-stone-900 text-stone-50 rounded-xl p-6 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Scale className="w-5 h-5 text-amber-400" />
            <h3 className="font-semibold text-base">Preparation for Legal Professional</h3>
          </div>
          <p className="text-xs text-stone-300 max-w-2xl leading-relaxed">
            Prepare strategic questions and actionable verification points for a consultation with your attorney based on the ambiguities, missing schedules, and provisions extracted from this agreement.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2 shrink-0">
          {data && (
            <>
              <button
                id="btn-copy-prep-notes"
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-100 transition-colors border border-stone-700"
                title="Copy markdown text to clipboard"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? "Copied" : "Copy Notes"}</span>
              </button>

              <button
                id="btn-download-dossier-md"
                onClick={handleDownloadMarkdown}
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-100 transition-colors border border-stone-700"
                title="Download Counsel Dossier as Markdown file"
              >
                <Download className="w-3.5 h-3.5 text-amber-400" />
                <span>Download .md</span>
              </button>

              <button
                id="btn-print-counsel-dossier"
                onClick={handlePrint}
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-100 transition-colors border border-stone-700"
                title="Print or Save as PDF"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print PDF</span>
              </button>
            </>
          )}

          <button
            id="btn-generate-lawyer-prep"
            onClick={handleGenerate}
            disabled={loading}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-amber-400 hover:bg-amber-300 text-stone-950 text-xs font-semibold transition-colors shadow-xs disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
            <span>{data ? "Regenerate Prep" : "Generate Lawyer Preparation"}</span>
          </button>
        </div>
      </div>

      {error && (
        <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-xs text-rose-800">
          {error}
        </div>
      )}

      {!data && !loading && (
        <div className="p-12 text-center bg-stone-50 rounded-xl border border-dashed border-stone-300 space-y-3">
          <FileQuestion className="w-8 h-8 text-stone-400 mx-auto" />
          <h4 className="text-sm font-semibold text-stone-800">
            No Preparation Checklist Generated Yet
          </h4>
          <p className="text-xs text-stone-500 max-w-md mx-auto">
            Click &ldquo;Generate Lawyer Preparation&rdquo; to formulate prioritized questions, an actionable review checklist, and missing schedules to gather for your lawyer.
          </p>
        </div>
      )}

      {data && (
        <div className="space-y-6">
          {/* Questions for Counsel */}
          <div className="bg-white border border-stone-200 rounded-xl p-5 shadow-xs space-y-4">
            <div className="flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-amber-600" />
              <h4 className="text-sm font-semibold text-stone-900">
                Focused Questions for Legal Counsel ({data.questionsForCounsel.length})
              </h4>
            </div>

            <div className="space-y-3">
              {data.questionsForCounsel.map((q, idx) => (
                <div
                  key={idx}
                  className="p-4 rounded-lg bg-stone-50 border border-stone-200 space-y-2"
                >
                  <div className="text-xs font-semibold text-stone-900 leading-snug">
                    {idx + 1}. {q.question}
                  </div>
                  <div className="text-xs text-stone-600">
                    <span className="font-medium text-stone-700">Why to ask: </span>
                    {q.reason}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Actionable Review Checklist */}
          <div className="bg-white border border-stone-200 rounded-xl p-5 shadow-xs space-y-4">
            <div className="flex items-center gap-2">
              <CheckSquare className="w-4 h-4 text-emerald-600" />
              <h4 className="text-sm font-semibold text-stone-900">
                Actionable Review Checklist ({data.reviewChecklist.length})
              </h4>
            </div>

            <div className="space-y-2">
              {data.reviewChecklist.map((item, idx) => {
                const getStatusColor = (st: string) => {
                  switch (st) {
                    case "negotiate":
                      return "bg-rose-50 text-rose-800 border-rose-200";
                    case "clarify":
                      return "bg-amber-50 text-amber-800 border-amber-200";
                    default:
                      return "bg-emerald-50 text-emerald-800 border-emerald-200";
                  }
                };

                return (
                  <div
                    key={idx}
                    className="p-3 rounded-lg border border-stone-200 flex items-center justify-between gap-3 text-xs bg-white"
                  >
                    <div className="flex items-center gap-2.5">
                      <span
                        className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded border ${getStatusColor(
                          item.status
                        )}`}
                      >
                        {item.status}
                      </span>
                      <span className="text-stone-800 font-medium">{item.item}</span>
                    </div>

                    <span className="text-[11px] text-stone-400 capitalize">
                      {item.category}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Missing Information Checklist */}
          {data.missingInformation.length > 0 && (
            <div className="bg-white border border-stone-200 rounded-xl p-5 shadow-xs space-y-3">
              <h4 className="text-sm font-semibold text-stone-900">
                Information & Attachments to Gather Before Consultation
              </h4>
              <ul className="space-y-1.5 text-xs text-stone-700">
                {data.missingInformation.map((info, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="text-amber-600 font-bold">•</span>
                    <span>{info}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
